
name: Trivy Security Scan for NGINX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Scan nginx:latest with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Date
        id: set-date
        run: echo "DATE=$(date +%m.%d.%Y)" >> $GITHUB_ENV

      - name: Create output directory
        run: mkdir -p "GitHub Actions/Trivy Automation"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Download Trivy vulnerability database
        run: trivy image --download-db-only

      - name: Run Trivy vulnerability scanner and show results
        run: |
          OUTPUT_FILE="GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
          echo "🔍 Running Trivy scan on nginx:latest..."
          trivy image --format json --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM,LOW -o "$OUTPUT_FILE" nginx:latest
          echo "📄 Scan results saved to $OUTPUT_FILE"
          echo "🧾 Displaying scan results:"
          cat "$OUTPUT_FILE"

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-${{ env.DATE }}
          path: GitHub Actions/Trivy Automation/scan-results-${{ env.DATE }}.json
